language: php
php:
- 5.6
- 7.0
- hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - php.time/vendor
    - php.time/dl

before_install: composer self-update && cd php.time

install: composer install --prefer-dist; make tzdata
script: vendor/bin/phpunit